Week4/wsmovies/config/routes.rb
Rails.application.routes.draw do
  get 'hello/sayhello'
  get 'hello/say/:something' => "hello#say"

  resources :directors
  resources :movies do
    resources :movie_roles, as: :role, path: "roles"
  end
  resources :actors
  get "/api/movies/:id" => "movies#show", as: "mystuff"

end

Week4/wsmovies/app/models/movie_role.rb
class MovieRole
  include Mongoid::Document
  field :character, type: String

  embedded_in :movie, touch: true
  belongs_to :actor
end

Week4/wsmovies/app/controllers/movie_roles_controller.rb
class MovieRolesController < ApplicationController
  before_action :set_movie
  before_action :set_movie_role, only: [:show, :edit, :update, :destroy]

  # GET /movie/:movie_id/roles
  # GET /movie/:movie_id/roles.json
  def index
    @movie_roles=@movie.roles
    fresh_when(@movie)
  end

  # GET /movie/:movie/roles/1
  # GET /movie/:movie/roles/1.json
  def show
  end

  # GET /movie/:movie/roles/new
  def new
    @movie_role = @movie.roles.build
  end

  # GET /movie_roles/1/edit
  def edit
  end

  # POST /movie/:movie_id/roles
  # POST /movie/:movie_id/roles.json
  def create
    last_modified=request.env["HTTP_IF_UNMODIFIED_SINCE"]
    fresh_when(@movie)   if last_modified  #get header values if condition supplied
    Rails.logger.debug("if_unmodified_since=#{last_modified}, current=#{response.last_modified}")

    if !last_modified || 
       (DateTime.strptime(last_modified,"%a, %d %b %Y %T %z") >= response.last_modified)

      @movie_role = @movie.roles.build(movie_role_params)
      respond_to do |format|
        if @movie_role.save
          fresh_when(@movie)
          format.html { redirect_to @movie, notice: 'Movie role was successfully created.' }
          format.json { render :"movies/show", status: :ok, location: @movie }
        else
          format.html { render :new }
          format.json { render json: @movie_role.errors, status: :unprocessable_entity }
        end
      end
    else
      render nothing: true, status: :conflict
    end
  end

  # PATCH/PUT /movie_roles/1
  # PATCH/PUT /movie_roles/1.json
  def update
    respond_to do |format|
      if @movie_role.update(movie_role_params)
        fresh_when(@movie)
        format.html { redirect_to @movie, notice: 'Movie role was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movie_roles/1
  # DELETE /movie_roles/1.json
  def destroy
    @movie_role.destroy
    respond_to do |format|
      format.html { redirect_to movie_roles_url, notice: 'Movie role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie_role
      @movie_role = @movie.roles.find_by(:id=>params[:id])
    end
    def set_movie
      @movie = Movie.find(params[:movie_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_role_params
      params.require(:movie_role).permit(:character, :actor_id)
    end
end

Week4/wsmovies/app/helpers/movie_roles_helper.rb
module MovieRolesHelper
end

Week4/wsmovies/app/views/movie_roles/_form.html.erb
<%= form_for([@movie,@movie_role], url: movie_role_path(@movie, @movie_role)) do |f| %>
  <% if @movie_role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie_role.errors.count, "error") %> prohibited this movie_role from being saved:</h2>

      <ul>
      <% @movie_role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :character %><br>
    <%= f.text_field :character %>
  </div>
  <div class="field">
    <%= f.label :actor_id %><br>
    <%= f.text_field :actor_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Week4/wsmovies/app/views/movie_roles/edit.html.erb
<h1>Editing Movie Role</h1>

<%= render 'form' %>

<%= link_to 'Show', movie_role_path(@movie, @movie_role) %> |
<%= link_to 'Back', movie_path(@movie) %>

Week4/wsmovies/app/views/movie_roles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Movie Roles</h1>

<table>
  <thead>
    <tr>
      <th>Character</th>
      <th>Actor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movie_roles.each do |movie_role| %>
      <tr>
        <td><%= movie_role.character %></td>
        <td><%= movie_role.actor_id %></td>
        <td><%= link_to 'Show', movie_role_path(@movie, movie_role) %></td>
        <td><%= link_to 'Edit', edit_movie_role_path(@movie, movie_role) %></td>
        <td><%= link_to 'Destroy', movie_role_path(@movie, movie_role), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie role', new_movie_role_path %>

Week4/wsmovies/app/views/movie_roles/new.html.erb
<h1>New Movie Role</h1>

<%= render 'form' %>

<%= link_to 'Back', movie_roles_path %>

Week4/wsmovies/app/views/movie_roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Character:</strong>
  <%= @movie_role.character %>
</p>

<p>
  <strong>Actor:</strong>
  <%= @movie_role.actor_id %>
</p>

<%= link_to 'Edit', edit_movie_role_path(@movie, @movie_role) %> |
<%= link_to 'Back', movie_path(@movie)  %>